name: Test & Lint

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
        description: 'DockerHub Username'
      DOCKERHUB_TOKEN:
        required: true
        description: 'DockerHub Personal Access Token'

jobs:
  python:
    name: Python
    runs-on: ubuntu-22.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Unit Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Lint (flake8)
        run: docker compose run --rm app sh -c "flake8"

  terraform:
    name: Terraform
    runs-on: ubuntu-22.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: TF lint
        run: |
          cd infra/
          docker compose run --rm terraform -chdir=deploy init -backend=false
          docker compose run --rm terraform -chdir=setup init -backend=false
          docker compose run --rm terraform -chdir=setup fmt -check
          docker compose run --rm terraform -chdir=setup validate
          docker compose run --rm terraform -chdir=deploy fmt -check
          docker compose run --rm terraform -chdir=deploy validate
