name: Test & Lint

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
        description: 'DockerHub Username'
      DOCKERHUB_TOKEN:
        required: true
        description: 'DockerHub Token Auth'

jobs:
  python:
    name: Python
    runs-on: ubuntu-22.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Unit Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Lint (flake8)
        run: docker compose run --rm app sh -c "flake8"
